-- DROP TABLE IF EXISTS HANH_TRINH CASCADE;
CREATE TABLE IF NOT EXISTS HANH_TRINH (
      MA_VANDON VARCHAR(15),
      TRANG_THAI INT,
      THOI_GIAN TIMESTAMP,
      MA_BUUCUC VARCHAR(50),
      NHANVIENPHAT VARCHAR(10),
      NGAY_HANHTRINH DATE
);
CREATE INDEX IF NOT EXISTS HANH_TRINH_IDX1 ON HANH_TRINH (MA_VANDON);
CREATE INDEX IF NOT EXISTS HANH_TRINH_IDX2 ON HANH_TRINH (TRANG_THAI);
CREATE INDEX IF NOT EXISTS HANH_TRINH_IDX3 ON HANH_TRINH (NGAY_HANHTRINH);
CREATE INDEX IF NOT EXISTS HANH_TRINH_IDX4 ON HANH_TRINH (MA_BUUCUC, TRANG_THAI, THOI_GIAN);
-- sinh NGAY_GUI_DATE từ NGAY_GUI_BP
CREATE OR REPLACE FUNCTION trg_update_ngay_hanhtrinh()
    RETURNS TRIGGER AS $$
BEGIN
    -- Gán giá trị cho NGAY_HANHTRINH dựa trên THOI_GIAN
    IF NEW.THOI_GIAN IS NOT NULL THEN
        NEW.NGAY_HANHTRINH := NEW.THOI_GIAN::DATE;
    END IF;
    -- Trả về bản ghi sau khi xử lý
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_update_ngay_hanhtrinh
    BEFORE INSERT OR UPDATE ON HANH_TRINH
    FOR EACH ROW
EXECUTE FUNCTION trg_update_ngay_hanhtrinh();