# docker compose to set up postgres with this configuration
# POSTGRES.USER: "postgres"
# POSTGRES.PASSWD: "123456"

version: '3.1'

services:
  postgres:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
    volumes:
      - ./.tmp/postgres/data:/var/lib/postgresql/data
      - ./sql/init-sql/postgres:/docker-entrypoint-initdb.d